### ISSUE TITLE
Having difficulties with python when building

### ISSUE THREAD

**Issue by MuratOzsoyler** [gthparch/macsim#52]
Hi,

I am getting some errors with build scripts in python.

Initially I attempted to compile with `python 3.9` and got errors regarding `ConfigParser`. Internet search revealed that his may be due to python version as the name of the `ConfigParser` module changed to `configparser`.

Due to this problem I installed `python 2.7`. But this time I get this error:
```
scons: Reading SConscript files ...
AttributeError: '_Environ' object has no attribute 'iteritems':
  File "/mnt/c/Users/hp1/Desktop/doga/assignment3/macsim/SConstruct", line 63:
    pre_compile_check()
  File "/mnt/c/Users/hp1/Desktop/doga/assignment3/macsim/SConstruct", line 51:
    for key,val in os.environ.iteritems():
```

How can I solve this? Any ideas?

Thanks in advance.

Configuration:
- Windows 10
- WSL 2
- ArchLinux

**Comment by hyesoon** [comment]
The build system has not tested on windows. Can you try to use mac or Linux?

**Comment by MuratOzsoyler** [comment]
Thank you for your reply.

Actually I tried to build on Linux. As you would notice the configuration above, I ran the build.py on Windows Subsystem for Linux which is an ArchLinux system running under Windows 10 OS. 

I even run Haskell compiler for Linux, compiling programs which link with GTK3 for Linux and run them under same configuration, serving X11 on Windows. So this compilation should not be a problem.

The problem is, build.py and related scripts are for python 2 as far as I can tell. So they don't run under python 3 (so `ConfigParser` module can not be found). On the other hand, when I run `build.py` under python 2.7, at some point some other script is started with default python 3 and I get `iteritems` error (certainly because the `_Environ` object API is changed in python 3). I  ask for a solution for this problem.

**Comment by hyesoon** [comment]
AFAIK, we don't use python 3. The build system is built a long time ago. Sorry,
 we don't have enough man power to investigate this problem. The best option is you try on ubuntu where we tested our build system.

**Comment by jiashenC** [comment]
From what I can tell, the error is from the Scons config file [SConstruct](https://github.com/gthparch/macsim/blob/master/SConstruct). The file indicates the python binary in shebang line. Are you sure your `/usr/bin/python` binary is the correct python version? Easy way to debug is to add `print(sys.version)` in the SConstruct to make sure it uses the expected python version.

**Comment by MuratOzsoyler** [comment]
Thanks for replying. Definitely this is a python version problem as I mentioned before.

What I am asking is whether there is a way to circumvent the problem temporarily, using some environment variables or configuration for example.

Even though I don't use it, I don't want to uninstall python 3, due to the packages that may depend on it.

**Comment by jiashenC** [comment]
You can try temporarily removing the shebang line in SConstruct.

**Comment by MuratOzsoyler** [comment]
Sorry for the late answer.

I'll install a fresh ArchLinux under WSL which contains only Python 2 as soon as I find enough time.

Many thanks for your suggestions.
